"""add phone to users

Revision ID: 4ad5357bce6f
Revises: c7f167ddbd74
Create Date: 2025-09-08 13:39:27.309490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad5357bce6f'
down_revision = 'c7f167ddbd74'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
