"""add user and fk relations

Revision ID: 6bf91c2f6b5f
Revises: 85073a493070
Create Date: 2025-09-08 12:43:58.294593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf91c2f6b5f'
down_revision = '85073a493070'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.add_column('case', sa.Column('owner_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_case_owner_id'), 'case', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'case', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_caseevent_actor_id'), 'caseevent', ['actor_id'], unique=False)
    op.create_foreign_key(None, 'caseevent', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.add_column('note', sa.Column('author_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_note_author_id'), 'note', ['author_id'], unique=False)
    op.create_foreign_key(None, 'note', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_index(op.f('ix_note_author_id'), table_name='note')
    op.drop_column('note', 'author_id')
    op.drop_constraint(None, 'caseevent', type_='foreignkey')
    op.drop_index(op.f('ix_caseevent_actor_id'), table_name='caseevent')
    op.drop_constraint(None, 'case', type_='foreignkey')
    op.drop_index(op.f('ix_case_owner_id'), table_name='case')
    op.drop_column('case', 'owner_id')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
