"""init schema

Revision ID: 85073a493070
Revises: 
Create Date: 2025-09-08 12:34:09.966300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85073a493070'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'sent', 'won', 'lost', name='casestatus'), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('letter', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_created_at'), 'case', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_id'), 'case', ['id'], unique=False)
    op.create_index(op.f('ix_case_owner'), 'case', ['owner'], unique=False)
    op.create_index(op.f('ix_case_reason'), 'case', ['reason'], unique=False)
    op.create_index(op.f('ix_case_status'), 'case', ['status'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('stored_path', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_case_id'), 'attachment', ['case_id'], unique=False)
    op.create_table('caseevent',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caseevent_action'), 'caseevent', ['action'], unique=False)
    op.create_index(op.f('ix_caseevent_at'), 'caseevent', ['at'], unique=False)
    op.create_index(op.f('ix_caseevent_case_id'), 'caseevent', ['case_id'], unique=False)
    op.create_index(op.f('ix_caseevent_category'), 'caseevent', ['category'], unique=False)
    op.create_table('checklistitem',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('extracted', sa.String(), nullable=True),
    sa.Column('na_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklistitem_case_id'), 'checklistitem', ['case_id'], unique=False)
    op.create_table('note',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_case_id'), 'note', ['case_id'], unique=False)
    op.create_index(op.f('ix_note_created_at'), 'note', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_created_at'), table_name='note')
    op.drop_index(op.f('ix_note_case_id'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_checklistitem_case_id'), table_name='checklistitem')
    op.drop_table('checklistitem')
    op.drop_index(op.f('ix_caseevent_category'), table_name='caseevent')
    op.drop_index(op.f('ix_caseevent_case_id'), table_name='caseevent')
    op.drop_index(op.f('ix_caseevent_at'), table_name='caseevent')
    op.drop_index(op.f('ix_caseevent_action'), table_name='caseevent')
    op.drop_table('caseevent')
    op.drop_index(op.f('ix_attachment_case_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_case_status'), table_name='case')
    op.drop_index(op.f('ix_case_reason'), table_name='case')
    op.drop_index(op.f('ix_case_owner'), table_name='case')
    op.drop_index(op.f('ix_case_id'), table_name='case')
    op.drop_index(op.f('ix_case_created_at'), table_name='case')
    op.drop_table('case')
    # ### end Alembic commands ###
