"""add payment model and link to case

Revision ID: c7f167ddbd74
Revises: 6bf91c2f6b5f
Create Date: 2025-09-08 12:58:09.648848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f167ddbd74'
down_revision = '6bf91c2f6b5f'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'successful', 'flagged', 'failed', name='paymentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_created_at'), 'payment', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_status'), 'payment', ['status'], unique=False)
    op.add_column('case', sa.Column('payment_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_case_payment_id'), 'case', ['payment_id'], unique=False)
    op.create_foreign_key(None, 'case', 'payment', ['payment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case', type_='foreignkey')
    op.drop_index(op.f('ix_case_payment_id'), table_name='case')
    op.drop_column('case', 'payment_id')
    op.drop_index(op.f('ix_payment_status'), table_name='payment')
    op.drop_index(op.f('ix_payment_created_at'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
